### ISSUE TITLE
BitcoinZ wallet virus issues

### ISSUE THREAD

**Issue by TheWhizzkid** [btcz/bitcoinz-wallet#49]
WTF is goin' on with the BTCZ wallet 1.4.0 for Windows? can't get it to work without my antivirus/anti-malware blocking every file as well as those created in the hidden folders.

Is the wallet really safe to use? - What I can't do is leave my computer which I have all cryptocurrency wallets stored, without a security & antivirus software.

Between mining software & wallets all of which showing up as malware is really a pain in the ass.

Any suggestions of an alternative BitcoinZ wallet and/or solution to these issues are greatly appreciated.

**Comment by cryptorex** [comment]
Visit our ANN original post here: https://ann.btcz.rocks 

and goto the wallets section - you'll find an alternative.

In crypto, you'll get a lot of false positives because of the nature of the way the wallets and mining software works AV detects resemblance to virus signatures.  The issue is the trust.  

Both of the substantive components of this wallet have their source code available.

This wallet is a fork from ZenCash and is written in Java: https://github.com/btcz/bitcoinz-wallet

The daemon portion (the .exe files packaged) are compiled from here: https://github.com/btcz/bitcoinz-win

You are free to review the code and determine if there is anything malicious, or alternatively - build the components from scratch and run them through your 'AV' and observe the results.
