### ISSUE TITLE
Wallet.DB missing addresses after EOF error, upgrade and reindex. Are my funds safu?

### ISSUE THREAD

**Issue by anthonyadavisii** [btcz/bitcoinz-wallet#62]
I have the same problem as Gofioamasado had in this thread https://github.com/btcz/bitcoinz-wallet/issues/33. So it looks like in my last send to a transparent address, the the remaining unspent balance was sent to a randomly generated address. I did not export the private key but had my wallet.db unencrypted so figured no issue.

Well come to find I ran into the EOF error to my horror. After investigating, I downloaded the patched wallet (which strangely did not have an incremented version) after performing a backup and reindex. After it was complete, I was finally able to open my wallet but found I had a zero balance. How do I recover from this situation?

Would the wallet overwrite my wallet.db? If so, this seems to be a poor design choice resulting in the loss of over 300k BTCZ. Moreover, there should be a dialog box on send to transparent address informing the user of this risk and that private key should be exported immediately after such transactions. Never did I think the client would overwrite my wallet.db...

I hope that this project will be able to redeem itself but as of now I have over 300k BTC in an address that I can't seem to access any longer. If not, think others need to be aware of the issue stated. :(

https://explorer.btcz.rocks/address/t1RWFSERkGjwLYJd7EVEEBKsNdJebK5AoFk

**Comment by cryptorex** [comment]
> I hope that this project will be able to redeem itself

Sorry, but the project has nothing to do with you not practicing proper backup procedures.  

> After investigating, I downloaded the patched wallet (which strangely did not have an incremented version

Versioning for major upgrades makes a lot of sense, our latest release has had minor changes, especially to the deprecation height while we work on testing other upgrades.  No need for version change, as we need to stay aligned with zcash core node versioning as best as we can.

> Would the wallet overwrite my wallet.db? 

Absolutely not, running a full node wallet that already has an existing wallet.dat file will not overwrite it.  If that were the design then you would have a new wallet.dat file EVERY TIME you run it again.  You need to have had a backup of your wallet.dat file or the private keys exported. 

> So it looks like in my last send to a transparent address, the the remaining unspent balance was sent to a randomly generated address. 

This is the way standard UTXO blockchains work, its called a 'change addresses'.  It sends the remaining amount to another address and is by design.

I've used the full node wallet for years and I don't have any issues with it.  The EOF errors usually have noting to do with your wallet, but instead it has to do with the blockchain needing to be reindexed.  

Just about every release tells you to backup your wallet.dat file before doing anything else.

Some suggestions:

- I would suggest you check your `%appdata%\BitcoinZ` or `%appdata%` folder to see if you find a wallet.dat file somewhere else you might have forgotten where you put it.
- Download FTK Imager (free forensic tool) and mount your drive and navigate to the `%appdata%\BitcoinZ` folder in FTK Imager and check for a wallet.dat file that has a red X, right-click and export the file.  This might allow you to recover your wallet.dat file.  The only way that file could be missing is by intentional deletion or by something else unrelated to wallet functionality.

**Comment by anthonyadavisii** [comment]
So, I when I created my initial wallet, backed up all my keys to a password manager. I think what I failed to realize was the new addresses created on each tp tx had additional keys that I needed to backup. So, that was misunderstanding. 

It's really a mystery to me what happened to the old wallet.db. I think at some point I noticed it was not present in the folder during this process. At this point, I think the culprit would have been my AV. Had a support session with McAfee and they said it could happen but their answer was far from conclusive. I do think the dialogue box with a warning on transparent address sends would minimize the user ending up in this situation. 

Unfortunately, I had switched AV and uninstalled McAfee so now have no way to determine what had actually happened nor restore if it was a quarantine issue. It really sucks but thanks for at least confirming the design would preclude the client being responsible. 

Think I understand now that for these types of crypto (privacy coins) that use a priv per address. It throws me off as other cryptos I use only have one seed phrase I need to know vs many private keys that use utxo. Believe Sia may be one.

I'll give your recommendations a shot. Thanks for taking the time.
